/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TagsRouteImport } from './routes/tags'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as UsersUserIdRouteImport } from './routes/users/$userId'
import { Route as ProjectsSlugRouteImport } from './routes/projects/$slug'
import { Route as BlueprintsNewRouteImport } from './routes/blueprints/new'
import { Route as BlueprintsBlueprintIdRouteImport } from './routes/blueprints/$blueprintId'
import { Route as BlueprintsBlueprintIdEditRouteImport } from './routes/blueprints/$blueprintId/edit'

const TagsRoute = TagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersUserIdRoute = UsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlueprintsNewRoute = BlueprintsNewRouteImport.update({
  id: '/blueprints/new',
  path: '/blueprints/new',
  getParentRoute: () => rootRouteImport,
} as any)
const BlueprintsBlueprintIdRoute = BlueprintsBlueprintIdRouteImport.update({
  id: '/blueprints/$blueprintId',
  path: '/blueprints/$blueprintId',
  getParentRoute: () => rootRouteImport,
} as any)
const BlueprintsBlueprintIdEditRoute =
  BlueprintsBlueprintIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => BlueprintsBlueprintIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/tags': typeof TagsRoute
  '/blueprints/$blueprintId': typeof BlueprintsBlueprintIdRouteWithChildren
  '/blueprints/new': typeof BlueprintsNewRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/projects/': typeof ProjectsIndexRoute
  '/blueprints/$blueprintId/edit': typeof BlueprintsBlueprintIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/tags': typeof TagsRoute
  '/blueprints/$blueprintId': typeof BlueprintsBlueprintIdRouteWithChildren
  '/blueprints/new': typeof BlueprintsNewRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/projects': typeof ProjectsIndexRoute
  '/blueprints/$blueprintId/edit': typeof BlueprintsBlueprintIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/tags': typeof TagsRoute
  '/blueprints/$blueprintId': typeof BlueprintsBlueprintIdRouteWithChildren
  '/blueprints/new': typeof BlueprintsNewRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/projects/': typeof ProjectsIndexRoute
  '/blueprints/$blueprintId/edit': typeof BlueprintsBlueprintIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/tags'
    | '/blueprints/$blueprintId'
    | '/blueprints/new'
    | '/projects/$slug'
    | '/users/$userId'
    | '/projects/'
    | '/blueprints/$blueprintId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/tags'
    | '/blueprints/$blueprintId'
    | '/blueprints/new'
    | '/projects/$slug'
    | '/users/$userId'
    | '/projects'
    | '/blueprints/$blueprintId/edit'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/tags'
    | '/blueprints/$blueprintId'
    | '/blueprints/new'
    | '/projects/$slug'
    | '/users/$userId'
    | '/projects/'
    | '/blueprints/$blueprintId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  TagsRoute: typeof TagsRoute
  BlueprintsBlueprintIdRoute: typeof BlueprintsBlueprintIdRouteWithChildren
  BlueprintsNewRoute: typeof BlueprintsNewRoute
  ProjectsSlugRoute: typeof ProjectsSlugRoute
  UsersUserIdRoute: typeof UsersUserIdRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tags': {
      id: '/tags'
      path: '/tags'
      fullPath: '/tags'
      preLoaderRoute: typeof TagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$userId': {
      id: '/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof UsersUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blueprints/new': {
      id: '/blueprints/new'
      path: '/blueprints/new'
      fullPath: '/blueprints/new'
      preLoaderRoute: typeof BlueprintsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blueprints/$blueprintId': {
      id: '/blueprints/$blueprintId'
      path: '/blueprints/$blueprintId'
      fullPath: '/blueprints/$blueprintId'
      preLoaderRoute: typeof BlueprintsBlueprintIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blueprints/$blueprintId/edit': {
      id: '/blueprints/$blueprintId/edit'
      path: '/edit'
      fullPath: '/blueprints/$blueprintId/edit'
      preLoaderRoute: typeof BlueprintsBlueprintIdEditRouteImport
      parentRoute: typeof BlueprintsBlueprintIdRoute
    }
  }
}

interface BlueprintsBlueprintIdRouteChildren {
  BlueprintsBlueprintIdEditRoute: typeof BlueprintsBlueprintIdEditRoute
}

const BlueprintsBlueprintIdRouteChildren: BlueprintsBlueprintIdRouteChildren = {
  BlueprintsBlueprintIdEditRoute: BlueprintsBlueprintIdEditRoute,
}

const BlueprintsBlueprintIdRouteWithChildren =
  BlueprintsBlueprintIdRoute._addFileChildren(
    BlueprintsBlueprintIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  TagsRoute: TagsRoute,
  BlueprintsBlueprintIdRoute: BlueprintsBlueprintIdRouteWithChildren,
  BlueprintsNewRoute: BlueprintsNewRoute,
  ProjectsSlugRoute: ProjectsSlugRoute,
  UsersUserIdRoute: UsersUserIdRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
