/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TechnologiesRouteImport } from './routes/technologies'
import { Route as TagsRouteImport } from './routes/tags'
import { Route as SkillRouteImport } from './routes/skill'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DeviceRouteImport } from './routes/device'
import { Route as CliTokenRouteImport } from './routes/cli-token'
import { Route as CliRouteImport } from './routes/cli'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StacksIndexRouteImport } from './routes/stacks/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as UsersUserIdRouteImport } from './routes/users/$userId'
import { Route as StacksSlugRouteImport } from './routes/stacks/$slug'
import { Route as ProjectsSlugRouteImport } from './routes/projects/$slug'
import { Route as BlueprintsNewRouteImport } from './routes/blueprints/new'
import { Route as BlueprintsBlueprintIdRouteImport } from './routes/blueprints/$blueprintId'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminProjectsRouteImport } from './routes/admin/projects'
import { Route as AdminCommentsRouteImport } from './routes/admin/comments'
import { Route as AdminBlueprintsRouteImport } from './routes/admin/blueprints'
import { Route as BlueprintsBlueprintIdIndexRouteImport } from './routes/blueprints/$blueprintId/index'
import { Route as BlueprintsBlueprintIdEditRouteImport } from './routes/blueprints/$blueprintId/edit'

const TechnologiesRoute = TechnologiesRouteImport.update({
  id: '/technologies',
  path: '/technologies',
  getParentRoute: () => rootRouteImport,
} as any)
const TagsRoute = TagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillRoute = SkillRouteImport.update({
  id: '/skill',
  path: '/skill',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DeviceRoute = DeviceRouteImport.update({
  id: '/device',
  path: '/device',
  getParentRoute: () => rootRouteImport,
} as any)
const CliTokenRoute = CliTokenRouteImport.update({
  id: '/cli-token',
  path: '/cli-token',
  getParentRoute: () => rootRouteImport,
} as any)
const CliRoute = CliRouteImport.update({
  id: '/cli',
  path: '/cli',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StacksIndexRoute = StacksIndexRouteImport.update({
  id: '/stacks/',
  path: '/stacks/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersUserIdRoute = UsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const StacksSlugRoute = StacksSlugRouteImport.update({
  id: '/stacks/$slug',
  path: '/stacks/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlueprintsNewRoute = BlueprintsNewRouteImport.update({
  id: '/blueprints/new',
  path: '/blueprints/new',
  getParentRoute: () => rootRouteImport,
} as any)
const BlueprintsBlueprintIdRoute = BlueprintsBlueprintIdRouteImport.update({
  id: '/blueprints/$blueprintId',
  path: '/blueprints/$blueprintId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProjectsRoute = AdminProjectsRouteImport.update({
  id: '/admin/projects',
  path: '/admin/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCommentsRoute = AdminCommentsRouteImport.update({
  id: '/admin/comments',
  path: '/admin/comments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBlueprintsRoute = AdminBlueprintsRouteImport.update({
  id: '/admin/blueprints',
  path: '/admin/blueprints',
  getParentRoute: () => rootRouteImport,
} as any)
const BlueprintsBlueprintIdIndexRoute =
  BlueprintsBlueprintIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => BlueprintsBlueprintIdRoute,
  } as any)
const BlueprintsBlueprintIdEditRoute =
  BlueprintsBlueprintIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => BlueprintsBlueprintIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cli': typeof CliRoute
  '/cli-token': typeof CliTokenRoute
  '/device': typeof DeviceRoute
  '/login': typeof LoginRoute
  '/skill': typeof SkillRoute
  '/tags': typeof TagsRoute
  '/technologies': typeof TechnologiesRoute
  '/admin/blueprints': typeof AdminBlueprintsRoute
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/users': typeof AdminUsersRoute
  '/blueprints/$blueprintId': typeof BlueprintsBlueprintIdRouteWithChildren
  '/blueprints/new': typeof BlueprintsNewRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/stacks/$slug': typeof StacksSlugRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/admin/': typeof AdminIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/stacks/': typeof StacksIndexRoute
  '/blueprints/$blueprintId/edit': typeof BlueprintsBlueprintIdEditRoute
  '/blueprints/$blueprintId/': typeof BlueprintsBlueprintIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cli': typeof CliRoute
  '/cli-token': typeof CliTokenRoute
  '/device': typeof DeviceRoute
  '/login': typeof LoginRoute
  '/skill': typeof SkillRoute
  '/tags': typeof TagsRoute
  '/technologies': typeof TechnologiesRoute
  '/admin/blueprints': typeof AdminBlueprintsRoute
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/users': typeof AdminUsersRoute
  '/blueprints/new': typeof BlueprintsNewRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/stacks/$slug': typeof StacksSlugRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/admin': typeof AdminIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/stacks': typeof StacksIndexRoute
  '/blueprints/$blueprintId/edit': typeof BlueprintsBlueprintIdEditRoute
  '/blueprints/$blueprintId': typeof BlueprintsBlueprintIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cli': typeof CliRoute
  '/cli-token': typeof CliTokenRoute
  '/device': typeof DeviceRoute
  '/login': typeof LoginRoute
  '/skill': typeof SkillRoute
  '/tags': typeof TagsRoute
  '/technologies': typeof TechnologiesRoute
  '/admin/blueprints': typeof AdminBlueprintsRoute
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/users': typeof AdminUsersRoute
  '/blueprints/$blueprintId': typeof BlueprintsBlueprintIdRouteWithChildren
  '/blueprints/new': typeof BlueprintsNewRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/stacks/$slug': typeof StacksSlugRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/admin/': typeof AdminIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/stacks/': typeof StacksIndexRoute
  '/blueprints/$blueprintId/edit': typeof BlueprintsBlueprintIdEditRoute
  '/blueprints/$blueprintId/': typeof BlueprintsBlueprintIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cli'
    | '/cli-token'
    | '/device'
    | '/login'
    | '/skill'
    | '/tags'
    | '/technologies'
    | '/admin/blueprints'
    | '/admin/comments'
    | '/admin/projects'
    | '/admin/users'
    | '/blueprints/$blueprintId'
    | '/blueprints/new'
    | '/projects/$slug'
    | '/stacks/$slug'
    | '/users/$userId'
    | '/admin/'
    | '/projects/'
    | '/stacks/'
    | '/blueprints/$blueprintId/edit'
    | '/blueprints/$blueprintId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cli'
    | '/cli-token'
    | '/device'
    | '/login'
    | '/skill'
    | '/tags'
    | '/technologies'
    | '/admin/blueprints'
    | '/admin/comments'
    | '/admin/projects'
    | '/admin/users'
    | '/blueprints/new'
    | '/projects/$slug'
    | '/stacks/$slug'
    | '/users/$userId'
    | '/admin'
    | '/projects'
    | '/stacks'
    | '/blueprints/$blueprintId/edit'
    | '/blueprints/$blueprintId'
  id:
    | '__root__'
    | '/'
    | '/cli'
    | '/cli-token'
    | '/device'
    | '/login'
    | '/skill'
    | '/tags'
    | '/technologies'
    | '/admin/blueprints'
    | '/admin/comments'
    | '/admin/projects'
    | '/admin/users'
    | '/blueprints/$blueprintId'
    | '/blueprints/new'
    | '/projects/$slug'
    | '/stacks/$slug'
    | '/users/$userId'
    | '/admin/'
    | '/projects/'
    | '/stacks/'
    | '/blueprints/$blueprintId/edit'
    | '/blueprints/$blueprintId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CliRoute: typeof CliRoute
  CliTokenRoute: typeof CliTokenRoute
  DeviceRoute: typeof DeviceRoute
  LoginRoute: typeof LoginRoute
  SkillRoute: typeof SkillRoute
  TagsRoute: typeof TagsRoute
  TechnologiesRoute: typeof TechnologiesRoute
  AdminBlueprintsRoute: typeof AdminBlueprintsRoute
  AdminCommentsRoute: typeof AdminCommentsRoute
  AdminProjectsRoute: typeof AdminProjectsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  BlueprintsBlueprintIdRoute: typeof BlueprintsBlueprintIdRouteWithChildren
  BlueprintsNewRoute: typeof BlueprintsNewRoute
  ProjectsSlugRoute: typeof ProjectsSlugRoute
  StacksSlugRoute: typeof StacksSlugRoute
  UsersUserIdRoute: typeof UsersUserIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  StacksIndexRoute: typeof StacksIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/technologies': {
      id: '/technologies'
      path: '/technologies'
      fullPath: '/technologies'
      preLoaderRoute: typeof TechnologiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tags': {
      id: '/tags'
      path: '/tags'
      fullPath: '/tags'
      preLoaderRoute: typeof TagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skill': {
      id: '/skill'
      path: '/skill'
      fullPath: '/skill'
      preLoaderRoute: typeof SkillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/device': {
      id: '/device'
      path: '/device'
      fullPath: '/device'
      preLoaderRoute: typeof DeviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cli-token': {
      id: '/cli-token'
      path: '/cli-token'
      fullPath: '/cli-token'
      preLoaderRoute: typeof CliTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cli': {
      id: '/cli'
      path: '/cli'
      fullPath: '/cli'
      preLoaderRoute: typeof CliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stacks/': {
      id: '/stacks/'
      path: '/stacks'
      fullPath: '/stacks/'
      preLoaderRoute: typeof StacksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$userId': {
      id: '/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof UsersUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stacks/$slug': {
      id: '/stacks/$slug'
      path: '/stacks/$slug'
      fullPath: '/stacks/$slug'
      preLoaderRoute: typeof StacksSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blueprints/new': {
      id: '/blueprints/new'
      path: '/blueprints/new'
      fullPath: '/blueprints/new'
      preLoaderRoute: typeof BlueprintsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blueprints/$blueprintId': {
      id: '/blueprints/$blueprintId'
      path: '/blueprints/$blueprintId'
      fullPath: '/blueprints/$blueprintId'
      preLoaderRoute: typeof BlueprintsBlueprintIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/projects': {
      id: '/admin/projects'
      path: '/admin/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/comments': {
      id: '/admin/comments'
      path: '/admin/comments'
      fullPath: '/admin/comments'
      preLoaderRoute: typeof AdminCommentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/blueprints': {
      id: '/admin/blueprints'
      path: '/admin/blueprints'
      fullPath: '/admin/blueprints'
      preLoaderRoute: typeof AdminBlueprintsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blueprints/$blueprintId/': {
      id: '/blueprints/$blueprintId/'
      path: '/'
      fullPath: '/blueprints/$blueprintId/'
      preLoaderRoute: typeof BlueprintsBlueprintIdIndexRouteImport
      parentRoute: typeof BlueprintsBlueprintIdRoute
    }
    '/blueprints/$blueprintId/edit': {
      id: '/blueprints/$blueprintId/edit'
      path: '/edit'
      fullPath: '/blueprints/$blueprintId/edit'
      preLoaderRoute: typeof BlueprintsBlueprintIdEditRouteImport
      parentRoute: typeof BlueprintsBlueprintIdRoute
    }
  }
}

interface BlueprintsBlueprintIdRouteChildren {
  BlueprintsBlueprintIdEditRoute: typeof BlueprintsBlueprintIdEditRoute
  BlueprintsBlueprintIdIndexRoute: typeof BlueprintsBlueprintIdIndexRoute
}

const BlueprintsBlueprintIdRouteChildren: BlueprintsBlueprintIdRouteChildren = {
  BlueprintsBlueprintIdEditRoute: BlueprintsBlueprintIdEditRoute,
  BlueprintsBlueprintIdIndexRoute: BlueprintsBlueprintIdIndexRoute,
}

const BlueprintsBlueprintIdRouteWithChildren =
  BlueprintsBlueprintIdRoute._addFileChildren(
    BlueprintsBlueprintIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CliRoute: CliRoute,
  CliTokenRoute: CliTokenRoute,
  DeviceRoute: DeviceRoute,
  LoginRoute: LoginRoute,
  SkillRoute: SkillRoute,
  TagsRoute: TagsRoute,
  TechnologiesRoute: TechnologiesRoute,
  AdminBlueprintsRoute: AdminBlueprintsRoute,
  AdminCommentsRoute: AdminCommentsRoute,
  AdminProjectsRoute: AdminProjectsRoute,
  AdminUsersRoute: AdminUsersRoute,
  BlueprintsBlueprintIdRoute: BlueprintsBlueprintIdRouteWithChildren,
  BlueprintsNewRoute: BlueprintsNewRoute,
  ProjectsSlugRoute: ProjectsSlugRoute,
  StacksSlugRoute: StacksSlugRoute,
  UsersUserIdRoute: UsersUserIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  StacksIndexRoute: StacksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
