services:
  postgres:
    image: pgvector/pgvector:pg17
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: blueprints
      POSTGRES_USER: blueprints
      POSTGRES_PASSWORD: blueprints
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
