import { readFileSync } from 'node:fs';
import type { Stack } from '@blueprints/shared';
import chalk from 'chalk';
import type { Command } from 'commander';
import { ApiError, createApiClient, unwrapResponse } from '../lib/api.js';
import { getConfig } from '../lib/config.js';
import {
	type BlueprintIndexRow,
	buildBlueprintContent,
	buildSource,
	extractExcerpt,
	inferLayer,
	parseIndexTsv,
} from '../lib/sync.core.js';

interface SyncOptions {
	project?: string;
	stack?: string;
	layer?: string;
	repo?: string;
	dryRun?: boolean;
}

const DEFAULT_INDEX_PATH = 'docs/blueprints.tsv';
const SYNC_CHANGELOG = 'Synced from blueprint index';

async function fetchExistingBySlug(client: ReturnType<typeof createApiClient>, slug: string) {
	try {
		const res = await client.api.blueprints[':id'].$get({ param: { id: slug } });
		return await unwrapResponse(res);
	} catch (err) {
		if (err instanceof ApiError && err.status === 404) return null;
		throw err;
	}
}

function readExcerpt(row: BlueprintIndexRow): string | undefined {
	try {
		const [path, lineStr] = row.location.split(':');
		if (!path || !lineStr) return undefined;
		const fileContent = readFileSync(path, 'utf-8');
		return extractExcerpt(fileContent, Number(lineStr));
	} catch {
		return undefined;
	}
}

export function registerSyncCommand(program: Command) {
	program
		.command('sync [index]')
		.description(
			'Push blueprints from a blueprint skill TSV index (generated by index.sh) to the registry',
		)
		.option('--project <slug>', 'Publish under a project namespace (must be a member)')
		.option('--stack <stack>', 'Stack for synced blueprints (default: server)')
		.option('--layer <layer>', 'Layer fallback when globs are absent or unrecognized')
		.option('--repo <repo>', 'Repository identifier (e.g. owner/repo) recorded in the source field')
		.option('--dry-run', 'Show what would be pushed without calling the API')
		.action(async (index: string | undefined, opts: SyncOptions) => {
			const indexPath = index ?? DEFAULT_INDEX_PATH;

			let raw: string;
			try {
				raw = readFileSync(indexPath, 'utf-8');
			} catch {
				console.error(
					chalk.red(
						`✗ Index not found: ${indexPath}\n` +
							`  Generate it with the blueprint skill: bash .claude/skills/blueprint/index.sh`,
					),
				);
				process.exit(1);
			}

			const rows = parseIndexTsv(raw);
			if (rows.length === 0) {
				console.log(chalk.yellow(`No blueprints found in ${indexPath}`));
				return;
			}

			const stack = (opts.stack || 'server') as Stack;
			const client = createApiClient();
			const config = getConfig();

			let projectId: string | undefined;
			if (opts.project) {
				try {
					const res = await client.api.projects[':slug'].$get({ param: { slug: opts.project } });
					const project = await unwrapResponse(res);
					projectId = 'error' in project ? undefined : project.id;
				} catch {
					projectId = undefined;
				}
				if (!projectId) {
					console.error(chalk.red(`✗ Project not found: ${opts.project}`));
					process.exit(1);
				}
			}

			console.log(chalk.bold(`Syncing ${rows.length} blueprint(s) from ${indexPath}\n`));
			let created = 0;
			let updated = 0;
			let failed = 0;

			for (const row of rows) {
				const label = `${row.name} (${chalk.gray(row.id)})`;
				try {
					const excerpt = readExcerpt(row);
					const content = buildBlueprintContent(row, excerpt);
					const source = buildSource(opts.repo, row.location);
					const layer = opts.layer ?? inferLayer(row.globs);

					if (opts.dryRun) {
						const action = (await fetchExistingBySlug(client, row.id)) ? 'update' : 'create';
						console.log(
							chalk.gray(
								`  [dry-run] would ${action}: ${label} — layer: ${layer}, source: ${source}`,
							),
						);
						continue;
					}

					const existing = await fetchExistingBySlug(client, row.id);
					if (existing && !('error' in existing)) {
						await client.api.blueprints[':id'].$put({
							param: { id: existing.id },
							json: {
								name: row.name,
								slug: row.id,
								description: row.description,
								usage: row.usage,
								stack,
								layer,
								content,
								changelog: SYNC_CHANGELOG,
								source,
							},
						});
						updated++;
						console.log(chalk.blue(`↻ Updated: ${label}`));
					} else {
						const res = await client.api.blueprints.$post({
							json: {
								name: row.name,
								slug: row.id,
								description: row.description,
								usage: row.usage,
								stack,
								layer,
								content,
								source,
								projectId,
							},
						});
						const result = await unwrapResponse(res);
						if ('error' in result) {
							console.error(chalk.red(`✗ Failed to push ${label}: ${result.error}`));
							failed++;
							continue;
						}
						created++;
						const url = `${config.server}/blueprints/${result.id}`;
						console.log(chalk.green(`✓ Created: ${label}`));
						console.log(chalk.gray(`  ${url}`));
					}
				} catch (err) {
					failed++;
					const msg = err instanceof Error ? err.message : 'Unknown error';
					console.error(chalk.red(`✗ Failed to sync ${label}: ${msg}`));
				}
			}

			console.log(
				`\n${chalk.bold('Summary:')} ${chalk.green(`${created} created`)}, ${chalk.blue(`${updated} updated`)}, ${failed ? chalk.red(`${failed} failed`) : '0 failed'}`,
			);
			if (failed > 0) process.exitCode = 1;
		});
}
