import { readFileSync } from 'node:fs';
import { BLUEPRINT_LAYERS, type BlueprintLayer } from '@blueprints/shared';
import chalk from 'chalk';
import type { Command } from 'commander';
import { ApiError, createApiClient, unwrapResponse } from '../lib/api.js';
import { detectTechnologies, inferLayer, mergeTechnologies } from '../lib/classify.core.js';
import { getConfig } from '../lib/config.js';
import {
	buildBlueprintContent,
	buildSource,
	extractExcerpt,
	foreignProjects,
	parseIndexTsv,
	splitLocation,
} from '../lib/sync.core.js';

interface SyncOptions {
	project?: string;
	techno?: string;
	layer?: string;
	repo?: string;
	dryRun?: boolean;
}

const DEFAULT_INDEX_PATH = 'docs/blueprints.tsv';
const SYNC_CHANGELOG = 'Synced from blueprint index';

/**
 * Slugs are unique per project, so the lookup is scoped to `project` when the
 * sync targets one. Unscoped, an ambiguous slug is a 409 the caller reports.
 */
async function fetchExistingBySlug(
	client: ReturnType<typeof createApiClient>,
	slug: string,
	project: string | undefined,
) {
	try {
		const res = await client.api.blueprints[':id'].$get({
			param: { id: slug },
			query: project === undefined ? {} : { project },
		});
		return await unwrapResponse(res);
	} catch (err) {
		if (err instanceof ApiError && err.status === 404) return null;
		throw err;
	}
}

/** The exemplar file's content, or undefined when it cannot be read from the working directory. */
function readExemplar(path: string): string | undefined {
	try {
		return readFileSync(path, 'utf-8');
	} catch {
		return undefined;
	}
}

export function registerSyncCommand(program: Command) {
	program
		.command('sync [index]')
		.description(
			'Push blueprints from a blueprint skill TSV index (generated by index.sh) to the registry',
		)
		.option(
			'--project <slug>',
			'Publish under a project namespace (must be a member); slugs are unique per project',
		)
		.option(
			'--techno <names>',
			"Comma-separated technologies added to the ones detected from each exemplar's imports (e.g. Next.js,Oracle Database)",
		)
		.option(
			'--layer <layer>',
			`Layer for blueprints whose exemplar path and globs match no convention (${BLUEPRINT_LAYERS.join('|')}, default: domain)`,
		)
		.option('--repo <repo>', 'Repository identifier (e.g. owner/repo) recorded in the source field')
		.option('--dry-run', 'Show what would be pushed without calling the API')
		.action(async (index: string | undefined, opts: SyncOptions) => {
			const indexPath = index ?? DEFAULT_INDEX_PATH;

			let raw: string;
			try {
				raw = readFileSync(indexPath, 'utf-8');
			} catch {
				console.error(
					chalk.red(
						`✗ Index not found: ${indexPath}\n` +
							`  Generate it with the blueprint skill: bash .claude/skills/blueprint/index.sh`,
					),
				);
				process.exit(1);
			}

			const rows = parseIndexTsv(raw);
			if (rows.length === 0) {
				console.log(chalk.yellow(`No blueprints found in ${indexPath}`));
				return;
			}

			// Casing is kept: the registry creates unknown technologies under the name it receives
			const explicitTechnologies = (opts.techno ?? '')
				.split(',')
				.map((t) => t.trim())
				.filter(Boolean);
			if (opts.layer && !BLUEPRINT_LAYERS.includes(opts.layer as never)) {
				console.error(
					chalk.red(
						`✗ Invalid layer: ${opts.layer}\n  Allowed layers: ${BLUEPRINT_LAYERS.join(', ')}`,
					),
				);
				process.exit(1);
			}
			const client = createApiClient();
			const config = getConfig();

			let projectId: string | undefined;
			if (opts.project) {
				try {
					const res = await client.api.projects[':slug'].$get({ param: { slug: opts.project } });
					const project = await unwrapResponse(res);
					projectId = 'error' in project ? undefined : project.id;
				} catch {
					projectId = undefined;
				}
				if (!projectId) {
					console.error(chalk.red(`✗ Project not found: ${opts.project}`));
					process.exit(1);
				}
			}

			console.log(chalk.bold(`Syncing ${rows.length} blueprint(s) from ${indexPath}\n`));
			let created = 0;
			let updated = 0;
			let failed = 0;
			const fallbackLayer = (opts.layer ?? 'domain') as BlueprintLayer;
			const unclassified: string[] = [];

			for (const row of rows) {
				const label = `${row.name} (${chalk.gray(row.id)})`;
				try {
					const { path, line } = splitLocation(row.location);
					const exemplar = readExemplar(path);
					const excerpt =
						exemplar === undefined || line === undefined
							? undefined
							: extractExcerpt(exemplar, line, path);
					const content = buildBlueprintContent(row, excerpt);
					const source = buildSource(opts.repo, row.location);

					const inferredLayer = inferLayer(path, row.globs);
					const layer = inferredLayer ?? fallbackLayer;
					if (!inferredLayer) unclassified.push(row.id);

					// An unreadable exemplar detects nothing: leave the blueprint's technologies
					// untouched rather than replacing them with the explicit ones only
					const technologies =
						exemplar === undefined
							? explicitTechnologies.length > 0
								? explicitTechnologies
								: undefined
							: mergeTechnologies(detectTechnologies(path, exemplar), explicitTechnologies);

					const existing = await fetchExistingBySlug(client, row.id, opts.project);

					// Never overwrite another project's blueprint from an unscoped sync:
					// the same pattern-id legitimately exists in several projects.
					const owners = existing && !('error' in existing) ? existing.projects : [];
					const foreign = foreignProjects(owners, projectId);
					if (foreign.length > 0) {
						failed++;
						console.error(
							chalk.red(
								`✗ Skipped ${label}: belongs to project ${foreign.join(', ')} — pass --project to sync into a namespace`,
							),
						);
						continue;
					}

					if (opts.dryRun) {
						const action = existing ? 'update' : 'create';
						const layerNote = inferredLayer ? layer : `${layer} (fallback)`;
						console.log(
							chalk.gray(
								`  [dry-run] would ${action}: ${label} — layer: ${layerNote}, technologies: ${technologies?.join(', ') || '-'}, source: ${source}`,
							),
						);
						continue;
					}

					if (existing && !('error' in existing)) {
						const res = await client.api.blueprints[':id'].$put({
							param: { id: existing.id },
							query: {},
							json: {
								name: row.name,
								slug: row.id,
								description: row.description,
								usage: row.usage,
								technologies,
								layer,
								content,
								changelog: SYNC_CHANGELOG,
								source,
							},
						});
						// A rejected update throws: it must count as failed, not as updated
						await unwrapResponse(res);
						updated++;
						console.log(chalk.blue(`↻ Updated: ${label}`));
					} else {
						const res = await client.api.blueprints.$post({
							json: {
								name: row.name,
								slug: row.id,
								description: row.description,
								usage: row.usage,
								technologies,
								layer,
								content,
								source,
								projectId,
							},
						});
						const result = await unwrapResponse(res);
						if ('error' in result) {
							console.error(chalk.red(`✗ Failed to push ${label}: ${result.error}`));
							failed++;
							continue;
						}
						created++;
						const url = `${config.server}/blueprints/${result.id}`;
						console.log(chalk.green(`✓ Created: ${label}`));
						console.log(chalk.gray(`  ${url}`));
					}
				} catch (err) {
					failed++;
					const msg = err instanceof Error ? err.message : 'Unknown error';
					console.error(chalk.red(`✗ Failed to sync ${label}: ${msg}`));
				}
			}

			if (unclassified.length > 0) {
				console.log(
					chalk.yellow(
						`\n⚠ ${unclassified.length} blueprint(s) matched no layer convention and were filed under "${fallbackLayer}": ${unclassified.join(', ')}`,
					),
				);
			}
			console.log(
				`\n${chalk.bold('Summary:')} ${chalk.green(`${created} created`)}, ${chalk.blue(`${updated} updated`)}, ${failed ? chalk.red(`${failed} failed`) : '0 failed'}`,
			);
			if (failed > 0) process.exitCode = 1;
		});
}
